repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: detect-private-key
    - id: fix-byte-order-marker
    - id: no-commit-to-branch
    - id: trailing-whitespace
    - id: detect-private-key
    - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
        args: [--fix, --select, I]
      - id: ruff-format
