
name: Test Python package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Install poetry
        run: pipx install poetry

      - name: Install requirements
        run: poetry install --with dev --all-extras --no-root

      - name: Test (python-${{ matrix.python-version }}, ${{ matrix.os }}))
        run: poetry run pytest
