name: Test Python package

on:
  push:
    branches: [master, v2.0.0]
    paths:
      - "python-package/**"
      - ".github/workflows/ci-python.yml"
  pull_request:
    branches: [master, v2.0.0]
    paths:
      - "python-package/**"
      - ".github/workflows/ci-python.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install
        working-directory: python-package

      - name: Install dependencies
        run: uv sync --locked
        working-directory: python-package

      - name: Ruff linter check
        run: uv run ruff check .
        working-directory: python-package

      - name: Ruff format check
        run: uv run ruff format --check .
        working-directory: python-package

      - name: Setup config
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        working-directory: python-package
        run: uv run python ../.github/scripts/setup-config.py

      - name: Test (python-${{ matrix.python-version }}, ${{ matrix.os }})
        run: uv run pytest
        working-directory: python-package
