name: deploy-docs
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
      - python-package/
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install
        working-directory: python-package

      - name: Install dependencies
        run: uv sync --locked
        working-directory: python-package

      - name: Build and deploy docs
        working-directory: python-package
        run: uv run mkdocs gh-deploy --force --config-file ../docs/mkdocs.yml
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
